In [1]:
import numpy as np

Array unidimensional

In [5]:
arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


Array bidimensional

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array de zero e um

In [11]:
# Array unidimensional de 10 elementos
arr = np.zeros(10)
print(arr)

# Array bidimensional (matriz)
matriz = np.zeros([3, 5])
print(f'\n{matriz}')

# Array unidimensional de um
arr = np.ones(5)
print(f'\n{arr}')

# Array bidimensional de um
matriz = np.ones([3, 5])
print(f'\n{matriz}')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Operações básicas

In [13]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(f'Valor mínimo: {arr.min()}, índice: {arr.argmin()}')
print(f'Valor máximo: {arr.max()}, índice: {arr.argmax()}')

Valor mínimo: 1, índice: 0
Valor máximo: 4, índice: 3


In [ ]:
# Exemplo extra com trigonometria

x = arr
y = arr2

distancia_cm = np.hypot(x, y) * 100
angulo_graus = np.degrees(np.arctan2(y, x))

print(f'Distância em cm: {distancia_cm} \nÂngulo em graus: {angulo_graus}')

import math

a = 1
b = 5

dist = math.sqrt(a**2 + b**2) * 100
angulo = math.atan2(b, a) * (180/math.pi)

print(f'Distância: {dist} \nÂngulo: {angulo}')

# Com isso notamos que np é voltado para arrays e math para numeros normais

Distância em cm: [509.90195136 632.45553203 761.57731059 894.427191  ] 
Ângulo em graus: [78.69006753 71.56505118 66.80140949 63.43494882]
Distância: 509.9019513592784 
Ângulo: 78.69006752597979


In [20]:
print(f'Soma: {arr.sum()}, média: {arr.mean()}')
print(arr)

print(f"Soma índice a índice: {arr + arr2}")
print(f'Multiplicação índice a íncice: {arr * arr2}')

print(f'Concatenar dois arrays: {np.concatenate((arr, arr2))}')

Soma: 10, média: 2.5
[1 2 3 4]
Soma índice a índice: [ 6  8 10 12]
Multiplicação índice a íncice: [ 5 12 21 32]
Concatenar dois arrays: [1 2 3 4 5 6 7 8]


Remodelando forma do array

In [ ]:
arr = np.arange(9)
print(arr)

print()

matriz = arr.reshape([3, 3]) # valores diferentes dão erro no remodelamento
print(matriz)

print(f'\nTamanho array: {matriz.size}')
print(f'Quantidade de dimensões: {matriz.ndim}')
print(f'Modelo do array: {matriz.shape}')
print(f'Soma das colunas: {matriz.sum(axis=0)}')
print(f'Soma das linhas: {matriz.sum(axis=1)}')

# Broadcasting/escalar
print(f'\nOperação entre matriz e um valor escalar: \n{matriz * 5} \n{matriz / 2} \n{matriz - 5}')

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Tamanho array: 9
Quantidade de dimensões: 2
Modelo do array: (3, 3)
Soma das colunas: [ 9 12 15]
Soma das linhas: [ 3 12 21]

Operação entre matriz e um valor escalar: 
[[ 0  5 10]
 [15 20 25]
 [30 35 40]] 
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]] 
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]


Números aleatórios

In [8]:
import numpy as np

np.random.seed(5)

matriz = np.random.randint(0, 10, 10)
print(matriz)

print()

matriz = np.random.randint(0, 10, [5, 5])
print(matriz)

[3 6 6 0 9 8 4 7 0 0]

[[7 1 5 7 0]
 [1 4 6 2 9]
 [9 9 9 1 2]
 [7 0 5 0 0]
 [4 4 9 3 2]]


Identifica únicos e conta recorrências de repetições

In [10]:
arr = np.array([1, 2, 2, 3, 3, 4])

print(np.unique(arr))

# Conta quantas repetições cada número teve
print(np.unique(arr, return_counts=True))

[1 2 3 4]
(array([1, 2, 3, 4]), array([1, 2, 2, 1]))
