Questão 01:

In [1]:
import numpy as np

# Array com oito números 1
array_1 = np.ones(8, dtype=int)

# Array com oito números aleatórios entre 0 e 9
array_2 = np.random.randint(0, 10, 8)

# Soma dos dois arrays
resultado = array_1 + array_2

print("Array de 1's:", array_1)
print("Array aleatório:", array_2)
print("Array resultante:", resultado)

# Soma de todos os elementos
soma = np.sum(resultado)

print("Soma dos elementos:", soma)

# Reshape dependendo da soma
if soma >= 40:
    resultado = resultado.reshape(4, 2)
else:
    resultado = resultado.reshape(2, 4)

print("Matriz resultante:")
print(resultado)

Array de 1's: [1 1 1 1 1 1 1 1]
Array aleatório: [1 2 7 8 7 8 6 5]
Array resultante: [2 3 8 9 8 9 7 6]
Soma dos elementos: 52
Matriz resultante:
[[2 3]
 [8 9]
 [8 9]
 [7 6]]


Questão 02:

In [3]:
# Cria matriz 2x2 com zeros
campo = np.zeros((2, 2))

# Escolhe uma posição aleatória
linha_bomba = np.random.randint(0, 2)
coluna_bomba = np.random.randint(0, 2)

# Coloca o número 1
campo[linha_bomba, coluna_bomba] = 1

print("Mini Campo Minado!")
print("Escolha posições entre 0 e 1.")

jogadas = 0
acertou = False
posicoes_jogadas = []

while jogadas < 3:

    linha = int(input("Digite a linha (0 ou 1): "))
    coluna = int(input("Digite a coluna (0 ou 1): "))

    # Verifica se a posição já foi escolhida
    if (linha, coluna) in posicoes_jogadas:
        print("Você já escolheu essa posição!")
        continue

    posicoes_jogadas.append((linha, coluna))
    jogadas += 1

    # Verifica se encontrou o 1
    if campo[linha, coluna] == 1:
        acertou = True
        print("Game Over! :( Try Again!")
        break
    else:
        print("Essa posição está segura!")

# Se não encontrou o 1 depois de todas as posições seguras
if not acertou and len(posicoes_jogadas) == 3:
    print("Congratulations! You beat the game! :)")

Mini Campo Minado!
Escolha posições entre 0 e 1.
Game Over! :( Try Again!


Questão 03:

In [4]:
# Criando uma matriz 3x4
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Matriz:")
print(matriz)

# Número de linhas e colunas
linhas, colunas = matriz.shape

# Número total de elementos
total = linhas * colunas

print("Número de linhas:", linhas)
print("Número de colunas:", colunas)
print("Total de elementos:", total)

# Verifica se é par ou ímpar
if total % 2 == 0:
    print("A matriz poderia se tornar um vetor com quantidade PAR de elementos.")
else:
    print("A matriz poderia se tornar um vetor com quantidade ÍMPAR de elementos.")

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Número de linhas: 3
Número de colunas: 4
Total de elementos: 12
A matriz poderia se tornar um vetor com quantidade PAR de elementos.


Questão 04:

In [5]:
# Define a seed
np.random.seed(10)

# Cria matriz 4x4 com números de 1 até 50
matriz = np.random.randint(1, 51, (4, 4))

print("Matriz:")
print(matriz)

Matriz:
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]


a)

In [6]:
# Média de cada linha
media_linhas = np.mean(matriz, axis=1)

# Média de cada coluna
media_colunas = np.mean(matriz, axis=0)

print("Média de cada linha:")
print(media_linhas)

print("Média de cada coluna:")
print(media_colunas)

Média de cada linha:
[16.   33.75 34.5  23.75]
Média de cada coluna:
[29.75 24.25 33.75 20.25]


b)

In [7]:
maior_media_linhas = np.max(media_linhas)
maior_media_colunas = np.max(media_colunas)

print("Maior média das linhas:", maior_media_linhas)
print("Maior média das colunas:", maior_media_colunas)

Maior média das linhas: 34.5
Maior média das colunas: 33.75


c)

In [9]:
valores, quantidades = np.unique(matriz, return_counts=True)

print("Quantidade de aparições:")

for valor, quantidade in zip(valores, quantidades):
    print(valor, "aparece", quantidade, "vez(es)")

print("\nNúmeros que aparecem 2 vezes:")

for valor, quantidade in zip(valores, quantidades):
    if quantidade == 2:
        print(valor)

Quantidade de aparições:
1 aparece 2 vez(es)
9 aparece 1 vez(es)
10 aparece 2 vez(es)
16 aparece 1 vez(es)
26 aparece 1 vez(es)
29 aparece 1 vez(es)
30 aparece 2 vez(es)
37 aparece 1 vez(es)
41 aparece 1 vez(es)
43 aparece 1 vez(es)
49 aparece 1 vez(es)
50 aparece 2 vez(es)

Números que aparecem 2 vezes:
1
10
30
50


Questão 05:

In [10]:
# Matriz 3x3 de zeros
zeros = np.zeros((3, 3))

# Matriz 3x3 de uns
uns = np.ones((3, 3))

# Soma das matrizes
soma = zeros + uns

print("Matriz de zeros:")
print(zeros)

print("Matriz de uns:")
print(uns)

print("Soma:")
print(soma)

# Multiplicando por um escalar
escalar = 5

resultado = soma * escalar

print("Resultado multiplicado pelo escalar:")
print(resultado)

# Transformando em vetor
vetor = resultado.reshape(9)

print("Vetor:")
print(vetor)

Matriz de zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Soma:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Resultado multiplicado pelo escalar:
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Vetor:
[5. 5. 5. 5. 5. 5. 5. 5. 5.]


Questão 06:

In [11]:
# Cria o array de 10 até 30, pulando de 2 em 2
array = np.arange(10, 31, 2)

print("Array:")
print(array)

# Maior valor e seu índice
maior = np.max(array)
indice_maior = np.argmax(array)

# Menor valor e seu índice
menor = np.min(array)
indice_menor = np.argmin(array)

# Soma
soma = np.sum(array)

print("Maior valor:", maior)
print("Índice do maior valor:", indice_maior)

print("Menor valor:", menor)
print("Índice do menor valor:", indice_menor)

print("Soma dos elementos:", soma)

Array:
[10 12 14 16 18 20 22 24 26 28 30]
Maior valor: 30
Índice do maior valor: 10
Menor valor: 10
Índice do menor valor: 0
Soma dos elementos: 220


Questão 07:

In [12]:
# Define a seed
np.random.seed(7)

# Cria os dois arrays
array_1 = np.random.randint(1, 11, 5)
array_2 = np.random.randint(1, 11, 5)

print("Array 1:")
print(array_1)

print("Array 2:")
print(array_2)

# Concatena os arrays
array_concatenado = np.concatenate((array_1, array_2))

print("Array concatenado:")
print(array_concatenado)

# Transforma em matriz 2x5
matriz = array_concatenado.reshape(2, 5)

print("Matriz 2x5:")
print(matriz)

Array 1:
[ 5 10  7  4  4]
Array 2:
[ 8  8 10  8  9]
Array concatenado:
[ 5 10  7  4  4  8  8 10  8  9]
Matriz 2x5:
[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
