In [1]:
import numpy as np

In [3]:
mtz = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mtz)

print()

# buscando linha da matriz
print(mtz[0])

# buscando múltiplas linhas
print(mtz[0:2])

# buscando colunas
print()

# print(mtz[linas,colunas])
# print(mtz[inclusivo:])
print(mtz[:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]
[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]
 [7 8]]


Condições

In [4]:
print(mtz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
filter = mtz > 5

print(filter)

print(mtz[filter])

filter = mtz%2 == 0

print(f'\n{filter}')
print(mtz[filter])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


Trabalhando com padrões textuais

In [9]:
arr = np.array(['Python', 'NumPy', 'Pandas', 'MatPlotLib', 'Ciencias de Dados'])

In [10]:
print(arr)

['Python' 'NumPy' 'Pandas' 'MatPlotLib' 'Ciencias de Dados']


In [11]:
print(np.char.find(arr, 'u'))

[-1  1 -1 -1 -1]


In [12]:
print(np.char.startswith(arr, 'P'))

[ True False  True False False]


In [13]:
print(np.char.upper(arr))

['PYTHON' 'NUMPY' 'PANDAS' 'MATPLOTLIB' 'CIENCIAS DE DADOS']


In [14]:
print(np.char.isalpha(arr))

[ True  True  True  True False]


Importando arquivo de teste

In [2]:
dataset = np.loadtxt('arquivo.txt', delimiter=',',dtype=str)

In [3]:
print(f'TXT: {dataset}')

TXT: ['Python' 'NumPy' 'Pandas' 'MatPlotLib' 'Data Science']


In [4]:
np.savetxt('arquivo1.txt', dataset, fmt='%s')

In [5]:
np.save('arquivo.npy', dataset)

In [8]:
dataset1 = np.load('arquivo.npy')

In [9]:
print(f'NPY: {dataset1}')

NPY: ['Python' 'NumPy' 'Pandas' 'MatPlotLib' 'Data Science']


Importando dados de um dataset real

In [11]:
dataset = np.loadtxt('space.csv', delimiter=';', dtype=str, encoding='utf-8')

In [12]:
print(len(dataset))

4325


In [13]:
header = dataset[0]
body = dataset[1:]

filter = dataset[:, 1] == 'SpaceX'
SpaceX = dataset[filter]

print(len(SpaceX))

100
